[package]
name = "list"
version = "0.0.1"
authors = ["Wojciech Nawrocki <wjnawrocki+gh@protonmail.com>"]

[dependencies]
crossbeam = { git = "https://github.com/Vtec234/crossbeam", branch = "lazy-list-map" }
